
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "buttonless"
#opacity = 0.95
#blur = true
option_as_alt = "Both"
startup_mode = "Maximized"

[font]
size = 15

normal.family = "MesloLGS Nerd Font Mono"
